import { BaseStat, NewBaseStat } from '@/types/Character'

export const attributeKeyMap: BaseStat = {
    HP: 'HP',
    Atk: 'ATK',
    Def: 'DEF',
    EM: 'Elemental Mastery',
    ER: 'Energy Recharge',
    CritRate: 'CRIT Rate',
    CritDMG: 'CRIT DMG',
    Heal: 'Healing Bonus',
    Pyro: 'Pyro DMG Bonus',
    Cryo: 'Cryo DMG Bonus',
    Hydro: 'Hydro DMG Bonus',
    Elec: 'Electro DMG Bonus',
    Anemo: 'Anemo DMG Bonus',
    Geo: 'Geo DMG Bonus',
    Dendro: 'Dendro DMG Bonus',
    Phys: 'Physical DMG Bonus',
}

export const fullBaseStats: NewBaseStat = {
    HP: 0,
    ATK: 0,
    DEF: 0,
    'Elemental Mastery': 0,
    'Energy Recharge': 100,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Pyro DMG Bonus': 0,
    'Cryo DMG Bonus': 0,
    'Hydro DMG Bonus': 0,
    'Electro DMG Bonus': 0,
    'Anemo DMG Bonus': 0,
    'Geo DMG Bonus': 0,
    'Dendro DMG Bonus': 0,
    'Physical DMG Bonus': 0,
    'Healing Bonus': 0,
    'Shield Strength': 0,
    'Normal Attack DMG Bonus': 0,
    'Normal Attack Additive Bonus': 0,
    'Charged Attack DMG Bonus': 0,
    'Charged Attack Additive Bonus': 0,
    'Charged Attack Stamina Cost': 0,
    'Plunging Attack DMG Bonus': 0,
    'Plunging Attack Additive Bonus': 0,
    'Elemental Skill DMG Bonus': 0,
    'Elemental Skill CRIT Rate': 0,
    'Elemental Skill CRIT DMG': 0,
    'Elemental Skill Additive Bonus': 0,
    'Elemental Burst DMG Bonus': 0,
    'Elemental Burst CRIT Rate': 0,
    'Elemental Burst CRIT DMG': 0,
    'Elemental Burst Additive Bonus': 0,
    'Elemental Burst CD Reduction': 0,
    'All CD Reduction': 0,
    'All DMG Bonus': 0,
    'All Elemental DMG Bonus': 0,
    'Overloaded DMG Bonus': 0,
    'Burning DMG Bonus': 0,
    'Vaporize DMG Bonus': 0,
    'Melt DMG Bonus': 0,
    'Superconduct DMG Bonus': 0,
    'Swirl DMG Bonus': 0,
    'Electro-Charged DMG Bonus': 0,
    'Shattered DMG Bonus': 0,
    'Aggravate DMG Bonus': 0,
    'Spread DMG Bonus': 0,
    'Bloom DMG Bonus': 0,
    'Burgeon DMG Bonus': 0,
    'Hyperbloom DMG Bonus': 0,
    'Bountiful Core DMG Bonus': 0,
    'Pyro RES': 0,
    'Pyro RES Shred': 0,
    'Cryo RES': 0,
    'Cryo RES Shred': 0,
    'Hydro RES': 0,
    'Hydro RES Shred': 0,
    'Electro RES': 0,
    'Electro RES Shred': 0,
    'Anemo RES': 0,
    'Anemo RES Shred': 0,
    'Geo RES': 0,
    'Geo RES Shred': 0,
    'Dendro RES': 0,
    'Dendro RES Shred': 0,
    'Physical RES': 0,
    'Physical RES Shred': 0,
}

export const displayStats = [
    'HP',
    'ATK',
    'DEF',
    'Elemental Mastery',
    'Energy Recharge',
    'CRIT Rate',
    'CRIT DMG',
    'Healing Bonus',
    'Shield Strength',
    'Pyro DMG Bonus',
    'Cryo DMG Bonus',
    'Hydro DMG Bonus',
    'Electro DMG Bonus',
    'Anemo DMG Bonus',
    'Geo DMG Bonus',
    'Dendro DMG Bonus',
    'Physical DMG Bonus',
    'Normal Attack DMG Bonus',
    'Charge Attack DMG Bonus',
    'Plunge Attack DMG Bonus',
    'Elemental Skill DMG Bonus',
    'Elemental Burst DMG Bonus',
    'All DMG Bonus',
    'Overloaded DMG Bonus',
    'Burning DMG Bonus',
    'Vaporize DMG Bonus',
    'Melt DMG Bonus',
    'Superconduct DMG Bonus',
    'Swirl DMG Bonus',
    'Electro-Charged DMG Bonus',
    'Shattered DMG Bonus',
    'Aggravate DMG Bonus',
    'Spread DMG Bonus',
    'Bloom DMG Bonus',
    'Burgeon DMG Bonus',
    'Hyperbloom DMG Bonus',
    'Pyro RES',
    'Cryo RES',
    'Hydro RES',
    'Electro RES',
    'Anemo RES',
    'Geo RES',
    'Dendro RES',
    'Physical RES',
]

export const availableIcons = [
    'hp',
    'atk',
    'def',
    'elemental-mastery',
    'energy-recharge',
    'crit-rate',
    'crit-dmg',
    'healing-bonus',
    'shield-strength',
    'pyro-dmg-bonus',
    'cryo-dmg-bonus',
    'hydro-dmg-bonus',
    'electro-dmg-bonus',
    'anemo-dmg-bonus',
    'geo-dmg-bonus',
    'dendro-dmg-bonus',
    'physical-dmg-bonus',
]
