export const attributeSections = [
    {
        name: 'Basic Attributes',
        attributes: [
            'HP',
            'ATK',
            'DEF',
            'Elemental Mastery',
            'Energy Recharge',
            'CRIT Rate',
            'CRIT DMG',
        ],
    },
    {
        name: 'Basic Bonuses',
        attributes: [
            'Healing Bonus',
            'Shield Strength',
            'Pyro DMG Bonus',
            'Cryo DMG Bonus',
            'Hydro DMG Bonus',
            'Electro DMG Bonus',
            'Anemo DMG Bonus',
            'Geo DMG Bonus',
            'Dendro DMG Bonus',
            'Physical DMG Bonus',
        ],
    },
    {
        name: 'Ability Bonuses',
        attributes: [
            'Normal Attack DMG Bonus',
            'Charged Attack DMG Bonus',
            'Plunging Attack DMG Bonus',
            'Elemental Skill DMG Bonus',
            'Elemental Burst DMG Bonus',
            'All DMG Bonus',
        ],
    },
    {
        name: 'Elemental Bonuses',
        attributes: [
            'Overloaded DMG Bonus',
            'Burning DMG Bonus',
            'Vaporize DMG Bonus',
            'Melt DMG Bonus',
            'Superconduct DMG Bonus',
            'Swirl DMG Bonus',
            'Electro-Charged DMG Bonus',
            'Shattered DMG Bonus',
            'Aggravate DMG Bonus',
            'Spread DMG Bonus',
            'Bloom DMG Bonus',
            'Burgeon DMG Bonus',
            'Hyperbloom DMG Bonus',
        ],
    },
    {
        name: 'Elemental Resistance',
        attributes: [
            'Pyro RES',
            'Cryo RES',
            'Hydro RES',
            'Electro RES',
            'Anemo RES',
            'Geo RES',
            'Dendro RES',
            'Physical RES',
        ],
    },
]

export const displayStats = [
    'HP',
    'ATK',
    'DEF',
    'Elemental Mastery',
    'Energy Recharge',
    'CRIT Rate',
    'CRIT DMG',
    'Healing Bonus',
    'Shield Strength',
    'Pyro DMG Bonus',
    'Cryo DMG Bonus',
    'Hydro DMG Bonus',
    'Electro DMG Bonus',
    'Anemo DMG Bonus',
    'Geo DMG Bonus',
    'Dendro DMG Bonus',
    'Physical DMG Bonus',
    'Normal Attack DMG Bonus',
    'Charged Attack DMG Bonus',
    'Plunging Attack DMG Bonus',
    'Elemental Skill DMG Bonus',
    'Elemental Burst DMG Bonus',
    'All DMG Bonus',
    'Overloaded DMG Bonus',
    'Burning DMG Bonus',
    'Vaporize DMG Bonus',
    'Melt DMG Bonus',
    'Superconduct DMG Bonus',
    'Swirl DMG Bonus',
    'Electro-Charged DMG Bonus',
    'Shattered DMG Bonus',
    'Aggravate DMG Bonus',
    'Spread DMG Bonus',
    'Bloom DMG Bonus',
    'Burgeon DMG Bonus',
    'Hyperbloom DMG Bonus',
    'Pyro RES',
    'Cryo RES',
    'Hydro RES',
    'Electro RES',
    'Anemo RES',
    'Geo RES',
    'Dendro RES',
    'Physical RES',
]

export const availableIcons = [
    'hp',
    'atk',
    'def',
    'elemental-mastery',
    'energy-recharge',
    'crit-rate',
    'crit-dmg',
    'healing-bonus',
    'shield-strength',
    'pyro-dmg-bonus',
    'cryo-dmg-bonus',
    'hydro-dmg-bonus',
    'electro-dmg-bonus',
    'anemo-dmg-bonus',
    'geo-dmg-bonus',
    'dendro-dmg-bonus',
    'physical-dmg-bonus',
]
